services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-wolfi:9.1.3
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    mem_limit: 2g
    ports:
      - 9200:9200
    networks:
      - es_net
    volumes:
      - es_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:9.1.3
    container_name: kibana
    restart: unless-stopped
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_SERVICEACCOUNTTOKEN=${ES_KIBANA_TOKEN}
      - KIBANA_FLEET_SERVICE_TOKEN=${ES_FLEET_SERVER_TOKEN}
      - XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY=${XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY}
    ports:
      - 5601:5601
    networks:
      - es_net

  fleet-server:
    image: docker.elastic.co/elastic-agent/elastic-agent-complete-wolfi:9.1.3
    container_name: fleet-server
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - kibana
    environment:
      - FLEET_SERVER_ENABLE=true
      - FLEET_SERVER_INSECURE_TLS=true
      - FLEET_SERVER_INSECURE_HTTP=true
      - FLEET_SERVER_ELASTICSEARCH_HOST=http://elasticsearch:9200
      - FLEET_SERVER_SERVICE_TOKEN=${FLEET_SERVER_SERVICE_TOKEN}
      - FLEET_SERVER_POLICY_ID=fleet-server-policy
    ports:
      - 8220:8220
      - 8222:8222
    volumes:
      - fleet_data:/usr/share/elastic-agent
    networks:
      - es_net
  
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.135.0
    container_name: otel-collector
    restart: unless-stopped
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      # - 1888:1888 # pprof extension
      # - 8888:8888 # Prometheus metrics exposed by the Collector
      # - 8889:8889 # Prometheus exporter metrics
      # - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      # - 55679:55679 # zpages extension
    depends_on:
      - fleet-server
    networks:
      - es_net

  mysql:
    image: mysql:9.4.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Pass234.
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 512m
        reservations:
          memory: 256m
    networks:
      - es_net
  redis:
    image: redis:8.2.1
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_USER: redis
      REDIS_PASSWORD: Pass234.
    ports:
      - "6379:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - es_net

volumes:
  es_data:
    external: true
  fleet_data:
    external: true
  mysql_data:
    external: true
  redis_data:
    external: true

networks:
  es_net:
    external: true